outdir: ../resultados/runs_ploss_sintetica/gnn

model:
  arq: "GNN"
  layers: [] # Optuna
  K: [] # Optuna
  dropout: -1 # Optuna


data:
  red: 'uru'
  data_path: /home/iboero/unsup_uru/data/reduru_sintetica
  red_path: /home/iboero/unsup_uru/data/red_uru.p
  normalize_X: -1 # Optuna

training:
  device: 'cuda'
  num_epochs: 1500
  early_stopping: 180
  betas: [0.9, 0.999]
  initial_metric_epoch: 0
  seed: 42
  batch_size: -1 # Optuna
  lr: -1 # Optuna
  weight_decay: -1 # Optuna
  batch_norm: -1 # Optuna
  dual_coefs: [] # Optuna
