outdir: ../resultados/runs_ploss_norm
model:
  batch_norm: true
  model: GNN_local
  layers:
  - 3
  - 512
  - 512
  - 512
  - 1
  K:
  - 6
  - 6
  - 6
  - 6
  dropout: 0.13377150904390073
data:
  data_path: ../data/red118/
  red: '118'
  normalize_X: true
  normalize_Y: true
training:
  device: cuda
  batch_size: 64
  lr: 0.0008565352117270758
  num_epochs: 1500
  early_stopping: 30
  betas:
  - 0.9
  - 0.999
  weight_decay: 1.273962775671444e-05
  seed: 42
  metric_frec: 30
  initial_metric_epoch: 0
  dropout: 0