outdir: ../resultados/runs_ploss_finallll
model:
  batch_norm: true
  model: GNN_local
  layers:
  - 4
  - 64
  - 64
  - 64
  - 64
  - 2
  K:
  - 8
  - 8
  - 8
  - 8
  - 8
  dropout: 0.03673615556985472
data:
  data_path: ../data/reduru
  red: uru
  red_path: ../data/red_uru.p
  normalize_X: true
  normalize_Y: true
  target: null
training:
  device: cuda
  batch_size: 64
  lr: 0.00048645559125121954
  lr_gamma: 0.999
  num_epochs: 400
  early_stopping: 30
  betas:
  - 0.9
  - 0.999
  weight_decay: 3.936233331058011e-06
  seed: 42
  initial_metric_epoch: 501
  metric_frec: 501
