outdir: ../resultados/runs_ploss_sintetica/gnn
model:
  layers:
  - 4
  - 512
  - 512
  - 5
  K:
  - 4
  - 4
  - 4
  arq: GNN
  dropout: 0.011268544720390909
data:
  data_path: ../data/reduru_sintetica
  red: uru
  red_path: ../data/red_uru.p
  normalize_X: false
training:
  device: cuda
  batch_size: 128
  lr: 0.0003916356115028821
  num_epochs: 1500
  early_stopping: 180
  betas:
  - 0.9
  - 0.999
  weight_decay: 5.834249714079114e-06
  seed: 42
  initial_metric_epoch: 0
  batch_norm: false
  dual_coefs:
  - 41.9792346004738
  - 25.798842742839245
  - 0.00017008099339981515
  loss: nn
