outdir: ../resultados/runs_ploss_final/gnn
model:
  layers:
  - 4
  - 512
  - 512
  - 512
  - 5
  K:
  - 2
  - 2
  - 2
  - 2
  arq: GNN
  dropout: 0.03278282893199658
data:
  data_path: ../data/reduru
  red: uru
  red_path: ../data/red_uru.p
  normalize_X: true
training:
  device: cuda
  batch_size: 128
  lr: 0.0008529286895020931
  num_epochs: 1500
  early_stopping: 180
  betas:
  - 0.9
  - 0.999
  weight_decay: 1.944227689787086e-06
  seed: 42
  initial_metric_epoch: 0
  batch_norm: true
  dual_coefs:
  - 0.39089758489394016
  - 0.2742394448236727
  - 5.921879718824769e-06
  loss: nn
