outdir: ../resultados/runs

model:
  model: 'FCNN'
  layers: [] # Optuna
  K: [] # Optuna

data:
  data_path: ../data
  red: '30' # 30 o 118
  red_path: None
  normalize_X: False # OPTUNA

training:
  device: 'cuda'
  use_edge_weights: True
  num_epochs: 1500
  early_stopping: 30
  betas: [0.9, 0.999]
  seed: 42
  dropout: -1 # Optuna
  weight_decay: -1 # Optuna
  batch_norm: False # Optuna
  dual_coefs: [] #Optuna 
  batch_size: -1 #Optuna
  lr: -1 #Optuna