outdir: ../resultados/runs

model:
  model: 'FCNN'
  layers: [] #Optuna
  K: [] #Optuna


data:
  data_path: ../data
  red: '30' # 30 o 118
  red_path: None
  normalize_X: False

training:
  device: 'cuda'
  batch_size: -1 #Optuna
  lr: -1 #Optuna
  num_epochs: 1500
  early_stopping: 30
  betas: [0.9, 0.999]
  weight_decay: 0
  seed: 42
  initial_metric_epoch: 0
  batch_norm: False # Booleano
  use_edge_weights: True #Booleano
  dual_coefs: [] #Optuna # dual_acflow_real, dual_acflow_imag, dual_lines 
  node_weights: [ 1, 21, 26, 22, 12] # nodos (generadores) que se controlan con la variable alpha
  alpha_node_weights: 0
