outdir: ../resultados/runs_ploss_sintetica
model:
  batch_norm: false
  model: FCNN_global
  layers:
  - 4
  - 1024
  - 1024
  - 1024
  - 2
  K: []
  dropout: 0.19028171196907112
data:
  data_path: ../data/reduru_sintetica
  red: uru
  red_path: ../data/red_uru.p
  normalize_X: true
  normalize_Y: true
  target: null
training:
  device: cuda
  batch_size: 64
  lr: 5.8290097102579205e-05
  lr_gamma: 0.999
  num_epochs: 1500
  early_stopping: 30
  betas:
  - 0.9
  - 0.999
  weight_decay: 1.1984435476780816e-05
  seed: 42
  initial_metric_epoch: 501
  metric_frec: 501
