outdir: ../resultados/runs

model:
  model: FCNN_global
  batch_norm: None # Booleano
  layers: [] # Optuna
  K: [] # Optuna

data:
  data_path: ../data/red30
  red: '30'
  normalize_X: True # Optuna
  normalize_Y: True # Optuna

training:
  device: 'cuda'
  num_epochs: 1500
  betas: [0.9, 0.999]
  seed: 42
  early_stopping: 30

  batch_size: -1 # Optuna
  lr: -1 # Optuna
  weight_decay: -1 # Optuna
  dropout: -1 # Optuna